name: Polybot Infrastructure Terraform Main

on:
  workflow_dispatch:
    inputs:
      eu-west-2:
        description: 'London (eu-west-2)'
        required: false
        type: boolean
      eu-central-1:
        description: 'Frankfurt (eu-central-1)'
        required: false
        type: boolean

jobs:
  eu-west-2:
    if: ${{ github.event.inputs.eu-west-2 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: eu-west-2
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_EU_WEST_2 }}
      ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}


  eu-central-1:
    if: ${{ github.event.inputs.eu-central-1 == 'true' }}
    uses: ./.github/workflows/infra-provisioning-region.yaml
    with:
      region-code: eu-central-1
    secrets:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN_EU_CENTRAL_1 }}
      ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
