name: Polybot Infrastructure Terraform Specific Region

on:
  workflow_call:
    inputs:
      region-code:
        required: true
        type: string
    secrets:
      TELEGRAM_TOKEN:
        required: true
      ACCESS_KEY_ID:
        required: true
      SECRET_ACCESS_KEY:
        required: true
      SSH_PUBLIC_KEY:
        required: true


jobs:
  init_ecr:
    runs-on: ubuntu-latest
    outputs:
      ecr_name: ${{ steps.set-vars.outputs.ecr_name }}
      ecr_url: ${{ steps.set-vars.outputs.ecr_url }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./tf  # The directory containing your Terraform configuration files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.0

      - name: Terraform init
        run: terraform init

      - name: Terraform workspace select
        run: terraform workspace select ${{ inputs.region-code }}.prod || terraform workspace new ${{ inputs.region-code }}.prod

      - name: Terraform validate
        run: terraform validate

      - name: Terraform apply
        run: |
          export TF_VAR_sshPubKey="${{ secrets.SSH_PUBLIC_KEY }}"
          export TF_VAR_botToken=${{ secrets.TELEGRAM_TOKEN }}
          terraform apply -target module.poly_ecr -auto-approve -var-file=region.${{ inputs.region-code }}.prod.tfvars
          $(terraform output -json | jq -r '@sh "export EXAMPLE1=\(.ecr_name.value)\nexport EXAMPLE2=\(.ecr_url.value)"')
          echo "${EXAMPLE1}"
          echo "ecr_name=${example1}" >> $GITHUB_OUTPUT
          echo "ecr_url=${example2}" >> $GITHUB_OUTPUT

  first_build:
    needs:
      - init_ecr
    uses: ./.github/workflows/polybot-first-deployment.yaml
    with:
      ecr_name: ${{ needs.init_ecr.outputs.ecr_name }}
      ecr_url: ${{ needs.init_ecr.outputs.ecr_url }}
      region: ${{ inputs.region-code }}
    secrets:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}


  Terraform:
    needs:
      - first_build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: ./tf  # The directory containing your Terraform configuration files
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.2.0

      - name: Terraform init
        run: terraform init

      - name: Terraform workspace select
        run: terraform workspace select ${{ inputs.region-code }}.prod || terraform workspace new ${{ inputs.region-code }}.prod

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: | 
          export TF_VAR_sshPubKey="${{ secrets.SSH_PUBLIC_KEY }}"
          export TF_VAR_botToken=${{ secrets.TELEGRAM_TOKEN }}
          terraform plan -var-file=region.${{ inputs.region-code }}.prod.tfvars

      - name: Terraform apply
        run: |
          export TF_VAR_sshPubKey="${{ secrets.SSH_PUBLIC_KEY }}"
          export TF_VAR_botToken=${{ secrets.TELEGRAM_TOKEN }}
          terraform apply -auto-approve -var-file=region.${{ inputs.region-code }}.prod.tfvars
