name: Polybot first Microservice Deployment

on:
  workflow_dispatch:
    inputs:
      ecr_name:
        required: true
        type: string
        description: ecr name
      ecr_url:
        required: true
        type: string
        description: ecr url
      region:
        required: true
        type: string
        description: region

env:
  REGION: ${{ inputs.region }}

jobs:

  Build:
    outputs:
      image_ver: ${{ steps.build.outputs.image_ver }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v4

      - name: Build and push image
        id: build
        run: |
          cd polybot
                    
          # Login to ECR 
          export AWS_ACCESS_KEY_ID=${{ secrets.ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ${{ inputs.region }} | docker login --username AWS --password-stdin 019273956931.dkr.ecr.${{ inputs.region }}.amazonaws.com

          IMAGE_VER=prod-0.0.${{ github.run_number }}
          IMAGE_NAME="${{ inputs.ecr_name }}:$IMAGE_VER"
          docker build -t $IMAGE_NAME .
          docker tag $IMAGE_NAME 019273956931.dkr.ecr.${{ inputs.region }}.amazonaws.com/$IMAGE_NAME
          docker push 019273956931.dkr.ecr.${{ inputs.region }}.amazonaws.com/$IMAGE_NAME
          echo "image_ver=$IMAGE_VER" >> "$GITHUB_OUTPUT"
